// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcTZLLHCGNPIUF9glXJ7kKynKbFa2eQ2Y',
    appId: '1:557267483880:web:29499fa81265ee4d375d5d',
    messagingSenderId: '557267483880',
    projectId: 'chat-app-23c4d',
    authDomain: 'chat-app-23c4d.firebaseapp.com',
    storageBucket: 'chat-app-23c4d.appspot.com',
    measurementId: 'G-DWDE0T5LD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpDbPgi42DIn3zZOJemviwkWGkOQcHjHk',
    appId: '1:557267483880:android:4302b3897e0b8860375d5d',
    messagingSenderId: '557267483880',
    projectId: 'chat-app-23c4d',
    storageBucket: 'chat-app-23c4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxyFd1HkEXbXGkQ-RAntnWc3ajwh8XieE',
    appId: '1:557267483880:ios:82507b4900868506375d5d',
    messagingSenderId: '557267483880',
    projectId: 'chat-app-23c4d',
    storageBucket: 'chat-app-23c4d.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxyFd1HkEXbXGkQ-RAntnWc3ajwh8XieE',
    appId: '1:557267483880:ios:904dba4921a01aeb375d5d',
    messagingSenderId: '557267483880',
    projectId: 'chat-app-23c4d',
    storageBucket: 'chat-app-23c4d.appspot.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
